#!/bin/sh

# initialize graphite's database
export PYTHONPATH=/opt/graphite/webapp
export DJANGO_SETTINGS_MODULE=graphite.settings

# activate the virtual environment
. /opt/graphite/bin/activate

# create the database in a race-condition safe way
flock -x /opt/graphite/storage/graphite.db /initialization

exec /opt/graphite/bin/gunicorn --env DJANGO_SETTINGS_MODULE=graphite.settings --workers=1 --threads=4 --limit-request-line=0 --max-requests=1000 --timeout=300 --bind=0.0.0.0:8080 graphite.wsgi:application
