#!/bin/sh

# initialize graphite's database
export PYTHONPATH=/opt/graphite/webapp
export DJANGO_SETTINGS_MODULE=graphite.settings

# activate the virtual environment
. /opt/graphite/bin/activate

# create the database in a race-condition safe way
flock -x /opt/graphite/storage/graphite.db /initialization

exec /opt/graphite/bin/gunicorn graphite.wsgi:application --env DJANGO_SETTINGS_MODULE=graphite.settings --limit-request-line=0 "$@"
